FROM docker.io/openjdk:11-jre-slim

ARG VERSION=${version}

ADD target/libs /app/libs
ADD target/netconfsimulator-${VERSION}.jar /app/netconf-simulator.jar
CMD java -cp /app/libs/*:/app/netconf-simulator.jar org.onap.netconfsimulator.Main
