version: '3'
services:
  ves:
    container_name: ves
    image: nexus3.onap.org:10003/onap/org.onap.dcaegen2.collectors.ves.vescollector:latest
    ports:
      - "8082:8080"
      - "8444:8443"
    networks:
      - vesnetwork
      - ves-pnfsim
    volumes:
      - ./certservice/client-resources/client-volume-for-ves/keystore.jks:/opt/app/VESCollector/etc/keystore
      - ./certservice/client-resources/client-volume-for-ves/keystore.pass:/opt/app/VESCollector/etc/passwordfile
      - ./certservice/client-resources/client-volume-for-ves/truststore.jks:/opt/app/VESCollector/etc/truststore
      - ./certservice/client-resources/client-volume-for-ves/truststore.pass:/opt/app/VESCollector/etc/trustpasswordfile
  onap-dmaap:
    container_name: dmaap
    image: dmaap-simulator
    ports:
      - "3904:3904"
    networks:
      - vesnetwork
networks:
  vesnetwork:
    driver: bridge
  ves-pnfsim:
    external: true
